//Core
import v5Logo from './core/VampireMasqueradeV5Logo.webp'

import alchemyLogo from './rombo_disciplines/rombo_Alchemy.svg'
import animalismLogo from './rombo_disciplines/rombo_Animalism.svg'
import auspexLogo from './rombo_disciplines/rombo_Auspex.svg'
import bloodSorceryLogo from './rombo_disciplines/rombo_BloodSorcery.svg'
import celerityLogo from './rombo_disciplines/rombo_Celerity.svg'
import dominateLogo from './rombo_disciplines/rombo_Dominate.svg'
import fortitudeLogo from './rombo_disciplines/rombo_Fortitude.svg'
import obfuscateLogo from './rombo_disciplines/rombo_Obfuscate.svg'
import oblivionLogo from './rombo_disciplines/rombo_Oblivion.svg'
import potenceLogo from './rombo_disciplines/rombo_Potence.svg'
import presenceLogo from './rombo_disciplines/rombo_Presence.svg'
import proteanLogo from './rombo_disciplines/rombo_Protean.svg'

import banuHaqimSymbol from './clanSymbols/BanuHaqim.webp'
import brujahSymbol from './clanSymbols/Brujah.webp'
import gangrelSymbol from './clanSymbols/Gangrel.webp'
import hecataSymbol from './clanSymbols/Hecata.webp'
import lasombraSymbol from './clanSymbols/Lasombra.webp'
import malkavianSymbol from './clanSymbols/Malkavian.webp'
import ministrySymbol from './clanSymbols/Ministry.webp'
import nosferatuSymbol from './clanSymbols/Nosferatu.webp'
import ravnosSymbol from './clanSymbols/Ravnos.webp'
import salubriSymbol from './clanSymbols/Salubri.webp'
import toreadorSymbol from './clanSymbols/Toreador.webp'
import tremereSymbol from './clanSymbols/Tremere.webp'
import tzimisceSymbol from './clanSymbols/Tzimisce.webp'
import ventrueSymbol from './clanSymbols/Ventrue.webp'
import caitiffSymbol from './clanSymbols/Caitiff_symbol.png'
import thinBloodSymbol from './clanSymbols/Thinblood_symbol.png'
import ghoulSymbol from './clanSymbols/Ghoul.png'

import banuHaqimLogo from './clanLogos/Banu_Haqim_Logo.png'
import brujahLogo from './clanLogos/Brujah_logo.png'
import gangrelLogo from './clanLogos/Gangrel_logo.png'
import hecataLogo from './clanLogos/Hecata_logo.png'
import lasombraLogo from './clanLogos/Lasombra_logo.png'
import malkavianLogo from './clanLogos/Malkavian_logo.png'
import ministryLogo from './clanLogos/Ministry_logo.png'
import nosferatuLogo from './clanLogos/Nosferatu_logo.png'
import ravnosLogo from './clanLogos/Ravnos_logo.png'
import salubriLogo from './clanLogos/Salubri_logo.png'
import toreadorLogo from './clanLogos/Toreador_logo.png'
import tremereLogo from './clanLogos/Tremere_logo.png'
import tzimisceLogo from './clanLogos/Tzimisce_logo.png'
import ventrueLogo from './clanLogos/Ventrue_logo.png'
import caitiffLogo from './clanLogos/Caitiff_logo.png'
import thinBloodLogo from './clanLogos/Thinblood_logo.png'
import ghoulLogo from './clanLogos/Ghoul_logo.png'

import anarchLogo from './sectLogos/AnarchTitleV5.webp'
import autarkisLogo from "./sectLogos/Autarkis_logo.png"
import camarillaLogo from "./sectLogos/CamarillaTitleV5.webp"

import anarchSymbol from './sectSymbols/Anarch_symbol.png'
import autarkisSymbol from './sectSymbols/Independent_symbol.png'
import camarillaSymbol from './sectSymbols/Camarilla_symbol.png'

export {v5Logo, anarchLogo, anarchSymbol, autarkisLogo, autarkisSymbol, camarillaLogo, camarillaSymbol, alchemyLogo, animalismLogo, auspexLogo, bloodSorceryLogo, celerityLogo, dominateLogo, fortitudeLogo, obfuscateLogo, oblivionLogo, potenceLogo, presenceLogo, proteanLogo, banuHaqimLogo, brujahLogo, gangrelLogo, hecataLogo, lasombraLogo, malkavianLogo, ministryLogo, nosferatuLogo, ravnosLogo, salubriLogo, toreadorLogo, tremereLogo, tzimisceLogo, ventrueLogo, banuHaqimSymbol, brujahSymbol, gangrelSymbol, hecataSymbol, lasombraSymbol, malkavianSymbol, ministrySymbol, nosferatuSymbol, ravnosSymbol, salubriSymbol, toreadorSymbol, tremereSymbol, tzimisceSymbol, ventrueSymbol, caitiffLogo, caitiffSymbol, thinBloodSymbol, thinBloodLogo, ghoulSymbol, ghoulLogo}